import Main from "../../../../../../../componente/util/main"

export const objetoinicialCab = {
  COD_CLIENTE	                      :'',		
  COD_PERSONA	                      :'',		
  COD_PERSONA_ANT	                  :'',
  COD_MONEDA_LIMITE	                :'',		
  LIMITE_CREDITO	                  :'',
  COD_COBRADOR	                    :'',			
  RUC	                              :'',			
  DIRECCION	                        :'',			
  TELEFONO	                        :'',			
  DIAS_COBRO	                      :'',			
  PLAZO	                            :'',
  COD_ZONA	                        :'',			
  ESTADO	                          :'A',			
  COD_USUARIO	                      :sessionStorage.cod_usuario,			
  FEC_ALTA	                        :'',
  ENCARGADO	                        :'',			
  COD_CONDICION_VENTA	              :'',			
  DESC_CONDICION_VENTA              :'',
  NRO_JERARQUIA	                    :'',
  TIP_DOCUMENTO	                    :'',			
  TIP_CLIENTE	                      :'',			
  COD_CAUSAL	                      :'',			
  FEC_ESTADO                        :'',
  COMENTARIO	                      :'',			
  TIPO_IMPUESTO	                    :'',			
  FEC_ULTIMA_COMPRA                 :'',
  REPRESENTANTE	                    :'',			
  COD_CORPORACION	                  :'',			
  PUE_REDESCONTARSE	                :'',			
  COD_SUCURSAL	                    :'',			
  NRO_ORDEN                         :'',
  RUTA_FIRMA	                      :'',			
  COD_PER_CONTACTO	                :'',			
  FEC_ULT_COBRO                     :'',
  CARTA_GARANTIA	                  :'',			
  IMP_BARRAS	                      :'',			
  COD_DIRECCION	                    :'',			
  COD_DIRECCION_POR_DEFECTO	        :'',			
  COD_CATEGORIA	                    :'D',		
  IND_SOLICITUD_CREDITO	            :'',
  FEC_SOLICITUD_CREDITO	            :'',
  FEC_MODIF_LIMITE_CREDITO	        :'',
  FEC_HABILITACION_CREDITO	        :'',		
  COD_USUARIO_MODI	                :'',
  FEC_MODI	                        :'',
  NIVEL_AUTORIZACION                :'',
  CARGA_PRECIOS_NCR	                :'',
  COD_CONDICION_ENTREGA	            :'',
  SALDO_RH	                        :'',
  LIMITE_CREDITO_RH	                :'',
  COD_CUENTA_CLI	                  :'',
  COD_GRUPO_CLIENTE	                :'',
  IND_VARIAS_UM	                    :'N',
  IND_SUB_CLIENTE	                  :'N',
  COD_USUARIO_ALTA	                :'',
  COD_CLIENTE_ANT	                  :'',			
  IND_PORC_VTA	                    :'',
  IND_EMPLEADO	                    :'N',
  IND_CERCA	                        :'N',
  IND_SOLIC	                        :'N',		
  IND_COBRANZA	                    :'N',
  IND_REG_TURISMO	                  :'N',
  NRO_REG_ESPECIAL	                :'',
  IND_AUT_FIN	                      :'N',
  CLIENTE_FOZ	                      :'N',
  IND_INPASA	                      :'N',
  IND_OBSER	                        :'N',
  IND_ACUERDO_COM	                  :'N',
  IND_ESTRATEGICO	                  :'N',
  COD_VENDEDOR	                    :'',
  COD_CLIENTE_REF	                  :'',		
  AUT_COMERCIAL	                    :'N',
  AUT_DIR	                          :'N',
  IND_INFORMCONF	                  :'N',
  IND_PAGO_ELECT	                  :'N',
  FEC_VIG_PAG_ELECT                 :'',
  IND_DEMANDA	                      :'N',		
  ESP_ENTREGA	                      :'N',		
  IND_FACT_SEPSA	                  :'N',
  LONGITUD	                        :''	,	
  LATITUD	                          :''	,	
  IND_CADUCA_DATOS	                :'N',
  FEC_CADUCIDAD                     :'',
  NRO_TARJETA_CREDITO	              :'',		
  FOTO_CI_FRENTE                    :'',
  FOTO_CI_DORSO                     :'',
  IND_TARJETA	                      :'N',
  FEC_BAJA                          :'',
  IMPR_RECIBO	                      :'N',
  IND_JNJ	                          :'I',
  COD_CAT_VTA	                      :'E',
  IND_BON	                          :'N',
  ENVIADO_EGOND	                    :'N',
  // valor generico
  NOMBRE                            :'',
  NOMB_FANTASIA                     :'',
  DIRECCION_CAB                     :'',
  PROVINCIA                         :'',
  NRO_DOCUMENTO                     :'',
  NRO_DIG_VER                       :'',
  PAIS                              :'',
  insertDefault                     : true,
}

export const objetoInicialDet = {
  COD_EMPRESA	        :  '',			
  COD_CLIENTE	        :  '',			
  COD_SUBCLIENTE	    :  '',			
  DESCRIPCION	        :  '',			
  DIRECCION	          :  '',			
  COD_IDENT	          :  '',			
  ES_CLIENTE_PRI	    :  'N',			
  COD_PROVINCIA	      :  '',			
  COD_CIUDAD	        :  '',			
  COD_CLUSTER	        :  '',			
  CERCA_DE	          :  '',			
  COD_MONEDA_LIMITE	  :  '',			
  LIMITE_CREDITO	    :  '',
  BARRIO	            :  '',			
  COD_CAUSAL	        :  '',			
  ACTIVO	            :  'S',
  NRO_CALLE	          :  '',			
  COD_CLIENTE_REF	    :  '',			
  COD_SUBCLIENTE_REF	:  '',			
  COD_PAIS	          :  '',			
  LATITUD	            :  '',			
  LONGITUD	          :  '',			
  IND_CADUCA_DATOS	  :  '',			
  FEC_CADUCIDAD       :  '',
  TIP_CLIENTE	        :  '',			
  AUT_PERFIL	        :  'S',
  FOTO_FACHADA	      :  '',
  FEC_INGRESO	        :  Main.moment().format('DD/MM/YYYY HH:mm:ss'),
  IDEAL_REPARTO	      :  '',			
  LATITUD_COB	        :  '',			
  LONGITUD_COB	      :  '',			
  IND_COBERTURA	      :  '',			
  IND_JNJ	            :  'I',			
  COD_SUPERPRO	      :  '',
  EMAIL               : null,			
  insertDefault       : true,
}