export const objetoInicialCab = {
  COD_EMPRESA	          : sessionStorage.cod_empresa,	
  TIP_ENT_SAL	          : 'AJS',
  SER_ENT_SAL	          : 'A',
  NRO_ENT_SAL	          : '',
  TIP_COMPROBANTE_REF	  : '',			
  SER_COMPROBANTE_REF	  : '',
  NRO_COMPROBANTE_REF	  : '',
  FEC_ENT_SAL	          : '',
  COD_SUCURSAL	        : sessionStorage.cod_sucursal,
  DESC_SUCURSAL         : sessionStorage.desc_sucursal,
  COD_DEPOSITO	        : '',
  DESC_DEPOSITO	        : '',
  COD_MOTIVO	          : '',
  DESC_MOTIVO	          : '',
  IND_ENT_SAL	          : '',
  AFECTA_COSTO	        : '',
  COD_MONEDA	          : '',
  DESC_MONEDA	          : '',
  COD_PROVEEDOR	        : '',
  DESC__PROVEEDOR	      : '',
  OBSERVACION	          : '',
  TIP_CAMBIO_US	        : '',
  COD_USUARIO	          : sessionStorage.cod_usuario,
  FEC_ALTA	            : '',
  COD_USUARIO_MODI	    : '',
  FEC_MODI	            : '',
  TIP_CAMBIO	          : '',
  ESTADO	              : 'P',
  FEC_ESTADO	          : '',
  IND_UNIDAD_MEDIDA	    : 'S',
  COD_VEHICULO	        : '',
  COD_CENTRO	          : '',
  USA_WMS	              : 'N',
  COD_CAT_ALM	          : '' ,
  BLOQ_X_JEFE	          : 'N',
  BLOQ_X_GTE	          : 'N',
  BLOQ_X_DIREC	        : 'N',
  AUT_JEFE	            : 'S',
  AUT_GERENTE	          : 'S',		
  AUT_DIRECTOR	        : 'S',
  COD_POTRERO	          : '' ,
  COD_EMPLEADO	        : '' ,
  TIPO_COMPRA	          : 'G',
  // --
  insertDefault       : true,
}
export const objetoInicialDet = {
  COD_EMPRESA	          : '',
  TIP_ENT_SAL	          : '',
  SER_ENT_SAL	          : '',
  NRO_ENT_SAL	          : '',
  NRO_ORDEN	            : '',
  COD_SUCURSAL	        : '',
  IND_ENT_SAL	          : '',
  AFECTA_COSTO	        : '',
  COD_ARTICULO	        : '',
  COSTO_ULTIMO	        : '',
  COSTO_PROMEDIO	      : '',
  CANTIDAD	            : '',
  CANTIDAD_ANT	        : 0,
  COD_UNIDAD_MEDIDA	    : '',
  CANTIDAD_UB	          : '',
  NRO_LOTE	            : '',
  FEC_VENCIMIENTO       : '',
  COSTO_UNITARIO	      : '',
  COSTO_UB	            : '',
  COD_DIRECCION	        : '',
  MONTO_TOTAL	          : '',
  COSTO_ULTIMO_US	      : '',
  COSTO_PROMEDIO_US	    : '',
  COD_CAUSA	            : '',
  PESO	                : '',
  PESO_TOTAL	          : '',
  COSTO_CON_IVA_GS	    : '',
  GASTO_CON_IVA_GS	    : '',
  PRECIO_ULTIMO_COSTO	  : '',
  COSTO_ULT_CON_IVA_GS	: '',
  // --
  insertDefault         : true,
}