export const objetoInicialCab = {
  COD_EMPRESA	        : sessionStorage.cod_empresa,
  TIP_COMPROBANTE	    : 'PED',
  SER_COMPROBANTE	    : 'A',
  NRO_COMPROBANTE	    : '',
  COD_SUCURSAL	      :	sessionStorage.cod_sucursal,
  DESC_SUCURSAL       : sessionStorage.desc_sucursal,
  FEC_COMPROBANTE	    : '',
  COD_MOTIVO	        : '',
  COMENTARIO	        : '',
  COD_MONEDA          : 1,
  TIP_CAMBIO          : 1,
  ESTADO              : 'P',
  TIPO                : 'N',
  CLIENTE_OCASIONAL   : '000',
  IND_REPARTO         : 'N',
  SALDO_ANT           : 0,
  TIP_COMPROBANTE_REF : '',
  IND_VENTA           : '',
  TIP_CLIENTE         : '',
  // --
  insertDefault       : true,
}

export const objetoInicialDet = {
  COD_EMPRESA	      : sessionStorage.cod_empresa,
  TIP_COMPROBANTE	  : 'PED',
  SER_COMPROBANTE	  : 'A',
  NRO_COMPROBANTE	  : '',
  NRO_ORDEN	        : '',
  COD_SUCURSAL	    : '',
  COD_DEPOSITO	    : '',
  DESC_DEPOSITO     : '',
  COD_DEPOSITO_ENT	: '',
  DESC_DEPOSITO_ENT : '',
  COD_ARTICULO	    : '',
  NRO_LOTE	        : '',
  COD_UNIDAD_MEDIDA	: '',
  CANTIDAD	        : '',
  CANTIDAD_UB     	: '',
  COSTO_ULTIMO	    :  0,
  COSTO_PROMEDIO	  : '',
  COSTO_ULTIMO_US	  : '',
  COSTO_PROMEDIO_US	: '',
  COD_CAUSA	        : '',
  FEC_VENCIMIENTO	  : '',
  TIP_COMP_REF	    : '',
  SER_COMP_REF	    : '',
  NRO_COMP_REF	    : '',
  NRO_ORDEN_REF	    : '',
  COD_DIRECCION	    : '',
  COD_DIRECCION_DES	: '',
  ESTADO	          : '',
  USA_WMS	          : '',
  TIP_MOV	          : '',
  PALET_NRO	        : '',
  FEC_VENCIM_01	    : '',
  COD_UNID_MED_RES	: '',
  CANTIDAD_RES	    : '',
  CANTIDAD_UB_RES	  : '',
  COD_SUCURSAL_ENT	: '',
  // --
  insertDefault       : true,
}