const inicialCab = {
  COD_EMPRESA	      : sessionStorage.getItem('cod_empresa'),
  COD_SUCURSAL	    : '',
  TIP_MOV_CAJ	      : '',
  SER_MOV_CAJ	      : '',
  NRO_MOV_CAJ	      : '',
  FEC_MOV_CAJ	      : '',
  COD_CAJA	        : '',
  NRO_HABILITACION	: '',
  NUM_ASIENTO	      : '',
  ANULADO	          : '',
  FEC_ANULACION	    : '',
  COD_USUARIO	      : '',
  NRO_CUENTA	      : '',
  TOT_NRO_MOV_CAJ	  : '',
  COD_MONEDA	      : '',
  TIPO_CAMBIO	      : '',
  TIP_CAMBIO	      : '',
  FEC_ALTA	        : '',
  COD_CLIENTE	      : '',
  DESC_CLIENTE	    : '',
  COD_SUBCLIENTE	  : '',
  DIFERENCIA	      : '',
  NRO_COMPR_REF	    : '',
  TIP_COMPR_REF	    : 'NIN',
  SER_COMPR_REF	    : '',
  APLI_NCR_PARCIAL	: '',
  NRO_ASIENTO	      : '',
  TIP_CAMBIO_US	    : '',
  OBSERVACION	      : '',
  IND_CIERRE	      : '',
  IND_EXCEPCION	    : '',
  IND_APLICADO	    : '',
  NRO_BOLETA	      : '',
  IND_INPASA	      : '',
  insertDefault     : true,
}

const inicialRef = {
  COD_EMPRESA	      : sessionStorage.getItem('cod_empresa'),
  COD_MONEDA        : '',
  TIP_CAMBIO        : '',
  TIP_COMPROBANTE   : '',
  SER_COMPROBANTE   : '',
  NRO_COMPROBANTE   : '',
  COD_CLIENTE       : '',
  NRO_CUOTA	        : '',
  COD_SUBCLIENTE    : '',
  TOT_COMPROBANTE   : '',
  NRO_CUENTA_CLIENTE: '',
  COD_BANCO_CLIENTE : '',
  TIP_PLANILLA      : '',
  NRO_PLANILLA      : '',
  IMPORTE_ANT       : '',
  insertDefault     : true,

}

const inicialDet = {
  COD_EMPRESA	          : sessionStorage.getItem('cod_empresa'),
  COD_SUCURSAL	        :'',	
  NRO_SECUENCIA	        :'',	
  TIPO_TRANS	          :'',	
  SUB_TIPO_TRANS	      :'',	
  COD_PER_JURIDICA	    :'',	
  NRO_CUENTA	          :'',	
  COD_MONEDA_COBRO	    :'',	
  TIP_CAMBIO	          :'',	
  FEC_EMISION	          :'',	
  FEC_VENCIMIENTO	      :'',	
  TIP_DOCUMENTO	        :'',	
  SER_DOCUMENTO	        :'',	
  NRO_DOCUMENTO	        :'',	
  NRO_CUENTA_CAJA_CHICA	:'',	
  COD_BANCO_CAJA_CHICA	:'',	
  COD_USUARIO	          :'',	
  MONTO	                :'',	
  COD_BANCO_CLIENTE	    :'',	
  NOM_CLIENTE	          :'',	
  NRO_CUENTA_ANT	      :'',	
  NRO_CUENTA_DEP	      :'',	
  NRO_IDENTIFICACION	  :'',	
  NRO_FACTURA	          :'',	
  IMPORTE               :'',
  insertDefault         : true,
}
const main = {
  inicialCab,
  inicialRef,
  inicialDet
}

export default main;