export const ObjetoInicial = {
  COD_EMPRESA	          : sessionStorage.cod_empresa,
  TIP_COMPROBANTE	      : 'PRE',
  SER_COMPROBANTE	      : 'A',
  NRO_COMPROBANTE	      : '',
  COD_SUCURSAL	        : '',
  FEC_COMPROBANTE	      : '',
  COD_CLIENTE	          : '',
  COD_VENDEDOR	        : '',
  COD_CONDICION_VENTA	  : '',
  COD_LISTA_PRECIO	    : '',
  COD_MONEDA	          : '',
  COD_MONEDA_US	        : '2',
  TIP_CAMBIO	          : '',
  TOT_COMPROBANTE	      : '',
  TOT_GRAVADAS	        : '',
  TOT_EXENTAS	          : '',
  TOT_IVA	              : '',
  ESTADO	              :'P',
  FEC_ESTADO	          :'' ,
  COD_USUARIO	          :'' ,
  NRO_AUTORIZACION	    :'' ,
  FEC_VENCIMIENTO	      :'' ,
  TEL_CLIENTE	          : '',
  RUC	                  : '',
  PROCESADO	            : '',
  NOM_CLIENTE	          : '',
  DIR_CLIENTE	          : '',
  COMENTARIO	          : '',
  FEC_ALTA	            : '',
  ESTADO_REPARTO	      : '',
  CI	                  : '',
  TIP_CAMBIO_US	        : '',
  COD_DEPOSITO	        : '',
  BLOQUEADO_X_CRED	    : '',
  BLOQUEADO_X_PREC	    : '',
  BLOQUEADO_X_COND	    : '',
  COD_ZONA	            : '',
  COD_SUBCLIENTE	      : '',
  NOM_SUBCLIENTE	      : '',
  PORC_DESC_VAR	        : '',
  PORC_DESC_FIN	        : '',
  DESCUENTO_VAR	        : '',
  DESCUENTO_FIN	        : '',
  IND_REPARTO	          : '',
  BLOQUEADO_X_DESC_FIN	: '',
  BLOQUEADO_X_DESC_OTR	: '',
  IND_GENERICO	        : '',
  CLIENTE_PERSONAS	    : '',
  VENDEDOR_PERSONA  	  : '',
  LIMITE_CREDITO	      : '',
  SALDO	                : '',
  TIP_COMPROBANTE_REF	  : '',
  SER_COMPROBANTE_REF	  : '',
  NRO_COMPROBANTE_REF	  : '',
  NRO_SEQ_CEC         	: '',
  TIP_MOV_CAJ	          : '',
  SER_MOV_CAJ	          : '',
  NRO_MOV_CAJ         	: '',
  FEC_CIERRE	          : '',
  COD_SUPERVISOR	      : '',
  SUPERVISOR_PERSONA	  : '',
  BLOQ_X_VENT_PROG	    : '',
  IND_TELEV             : '',
  SIGLAS            	  : '',
  BLOQUEADO_X_BONIFIC   : '',
  COD_USUARIO_MODIFIC   : '',
  COD_MOTIVO_ANU        : '',
  TIP_COMPR_REF         : '',
  SER_COMPR_REF         : '',
  NRO_COMPR_REF         : '',			
  COD_SUCURSAL_ANT      : '',
  COD_DEPOSITO_ANT	    : '',
  OBS_ANU	              : '',
  COD_VEHICULO	        : '',
  IND_VENTA	            : '',
  IND_VISITA	          : '',
  LONGITUD	            : '',
  LATITUD	              : '',
  NRO_ORDEN_COMPRA	    : '',
  COD_PROMOCION	        : '',
  OBSERVACIONES	        : '',
  IND_LOGISTICA	        : '',
  IND_COMERCIAL	        : '',
  IND_REG_TURISMO	      : '',
  BLOQUEADO_X_VTO	      : '',
  ANULADO_POR	          : '',
  IND_COND_VTA	        : '',
  BLOQUEADO_X_OTROS   	: '',
  IND_AUT_DESC	        : '',
  OBS_AUT_DESC	        : '',
  IND_INPASA	          : '',
  IND_RH	              : '',
  COD_EMPLEADO        	: '',
  CANT_CUOTA	          : '',
  FEC_CALCULO	          : '',
  COD_CONCEPTO	        : '',
  IND_LIQ_FINAL	        : '',	
  TIP_COMP_REF	        : '',
  SER_COMP_REF	        : '',
  NRO_COMP_REF	        : '',
  IND_TRANS     	      : '',
  COD_GRUP_VEND	        : '',
  COD_CLIENTE_REF	      : '',
  IND_BON	              : '',
  IND_PRESENCIAL	      : '',
  BLOQUEADO_X_INGRESO	  : '',
  TIP_VTA_GANADO    	  : '',
  TIP_PLANILLA	        : '',
  NRO_PLANILLA	        : '',
  IND_PRONT_ENT	        : '',
  TIPTRA	              : '',
  ESTADO_CORREO	        :'P',
  insertDefault         :true
}


export const ObjetoInicialDet = {
  COD_EMPRESA	              :'',
  TIP_COMPROBANTE	          :'',
  SER_COMPROBANTE	          :'',
  NRO_COMPROBANTE	          :'',
  COD_ARTICULO	            :'',
  CANTIDAD	                :'',
  CANTIDAD_ANT	            :'',
  CANTIDAD_FACTURADA	      :'',
  PRECIO_UNITARIO	          :'',
  MONTO_TOTAL	              :'',
  TOTAL_IVA	                :'',
  COSTO_PROMEDIO	          :'',
  COD_UNIDAD_MEDIDA	        :'',
  CANTIDAD_UB	              : 1,
  PORC_IVA	                :'',
  ORDEN	                    :'',
  NRO_LOTE	                :'',
  COD_DEPOSITO	            :'',
  COD_IVA	                  :'',
  PRECIO_UNITARIO_C_IVA	    :'',
  COD_SUCURSAL	            :'',
  MONTO_TOTAL_CONIVA	      :'',
  PRECIO_UB	                :'',
  COSTO_ULTIMO	            :'',
  CANTIDAD_UB_S_STOCK	      :'',
  IND_MANEJA_STOCK	        :'',
  PORC_DESC_VAR	            :'',
  PORC_DESC_FIN	            :'',
  DESCUENTO_VAR	            :'',
  DESCUENTO_FIN	            :'',
  IND_BLOQUEADO	            :'',
  CANTIDAD_UB_ANT	          :'',
  PRECIO_LISTA	            :'',
  FEC_VENCIMIENTO	          :'',			
  PORC_COMISION	            :'',
  TIP_COMPROBANTE_REF	      :'',
  SER_COMPROBANTE_REF	      :'',
  NRO_COMPROBANTE_REF	      :'',
  NRO_ORDEN_REF	            :'',
  PRECIO_MIN	              :'',
  COD_UM	                  :'',
  COD_LINEA	                :'',
  PORC_COMISION_SUPERVISOR  :'',
  PORC_NEG	                :'',
  IND_VENTA	                :'',
  COD_ARTICULO_ORIGEN	      :'',
  IND_PROVISORIO	          :'',
  IND_REG_TURISMO	          :'',
  PRECIO_NEG	              :'',
  IND_TIP_PROD	            :'',
  IND_OTROS	                :'',
  IND_INPASA	              :'',
  MARG_UTIL	                :'',
  PRECIO_DIFERENCIA	        :'',
  NRO_PROMOCION	            :'',
  TIPO_PROMOCION	          :'',
  NRO_AUTORIZACION	        :'',
  COD_CLIENTE_REF	          :'',
  COD_SUBCLIENTE_REF	      :'',
  IND_BON	                  :'',
  IND_BON_CAU	              :'',
  PORC_GRAVADA	            :'',
  BLOQUEADO_X_INGRESO	      :'',
  PESO	                    :'',
  TOTAL_PESO	              :'',
  PESO_MUERTO	              :'',
  TOTAL_PESO_MUERTO	        :'',
  PORC_UTILIDAD	            :'',
  PESO_DESBASTE	            :'',
  TOTAL_PESO_DESBASTE	      :'',
  PORC_DESBASTE	            :'',
  PRECIO_X_PESO_C_IVA	      :'',
  FEC_VIGENCIA_PRECIO	      :'',			
  IND_PRONT_ENT	            :'',
  TIP_COMPR_REF	            :'',
  SER_COMPR_REF	            :'',
  NRO_COMPR_REF	            :'',
  COMENTARIO	              :'',
  MULT                      :'',
  DIV                       :'',
  DESCUENTO                 :0,
  DESCUENTO_ANT             :'',
  PORC_DESC                 :0,
  insertDefault             :true
}